version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000

  authserver:
    build:
      context: .
      dockerfile: AuthServer/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
  spa:
    build:
      context: .
      dockerfile: Spa/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - api

  mcpproxy:
    build:
      context: .
      dockerfile: MCPProxy/Dockerfile
    ports:
      - "8009:8009"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    depends_on:
      - authserver
