version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080

  spa:
    build:
      context: .
      dockerfile: Spa/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - api
